stages:
  - build

build:
  stage: build
  except:
    refs:
      - tags
  only:
    - master
  tags:
    - shell
    - zerotier
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - docker login -u gitlab-ci -p gitlab-ci https://$REGISTRY
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD http://$REGISTRY_MIRROR || true
  script:
    - mkdir -p .go
    - docker pull $REGISTRY/$CI_PROJECT_PATH:latest || true
    - docker build . --cache-from $REGISTRY/$CI_PROJECT_PATH:latest
      -t $REGISTRY/$CI_PROJECT_PATH:latest
      -t $REGISTRY_MIRROR/$CI_PROJECT_PATH:latest
      --build-arg GITLAB_TOKEN=$GITLAB_TOKEN
      --build-arg GITLAB_DOMAIN=$GITLAB_DOMAIN
      --build-arg RABBIT_HOST=$RABBIT_HOST
    - docker push $REGISTRY/$CI_PROJECT_PATH:latest
    - docker push $REGISTRY_MIRROR/$CI_PROJECT_PATH:latest || true
    - docker image rm $REGISTRY/$CI_PROJECT_PATH:latest
    - docker image rm $REGISTRY_MIRROR/$CI_PROJECT_PATH:latest
    - curl -X POST $DEPLOY_WEBHOOK